### ISSUE TITLE
Load Balancer Unhealthy

### ISSUE THREAD

**Issue by Malir1988** [aws-quickstart/quickstart-chainlinklabs-chainlink-node#23] opened 2021-11-12 13:08 UTC
I tried to created a chainlink node using this quickstart guide. (after the closed Issue / Hotfix)

For my tests a used the entry  point "Deploy Chainlink node into a new VPC on AWS"

![image](https://user-images.githubusercontent.com/71456816/141471835-b89210fa-ad3d-48e8-b626-973ef9d3ce94.png)

after the deployment is 100% complete:

![image](https://user-images.githubusercontent.com/71456816/141471746-147b56f5-2684-4320-bf48-e5c2d3c1f270.png)

 i see the following when i check the load balancer listeners:

![image](https://user-images.githubusercontent.com/71456816/141471981-423e4878-4626-4a80-bdfa-156576a542f7.png)

The nodes are not running. I configured everything as described in the guide, but I am not able to get the service / nodes running

**Comment by dangitsdavid** [comment] 2021-11-12 23:17
@Malir1988 can you share some logs from your CloudWatch (i.e., ChainlinkNodeInitLogGroup or ChainlinkLogs)? My suspicion is something related to your Chainlink node container not able to properly start so checking the status of the container would be a good start.

I've ran this deployment fresh and have not been able to run into the same issue. The ideal outcome would be one host from the target group will be unhealthy (this is the secondary node - because there is an advisory lock which prevents connection to the db), and another host will be marked as healthy (this is the primary node).

**Comment by Malir1988** [comment] 2021-11-13 06:20
Hello,

As far as i understand the logs the node is not able to connect to the database.

==> Chainlinklogs

[log-events-viewer-result_ChainlinkNodeInitLogGroup_1.csv](https://github.com/aws-quickstart/quickstart-chainlinklabs-chainlink-node/files/7531499/log-events-viewer-result_ChainlinkNodeInitLogGroup_1.csv)
[log-events-viewer-result_ChainlinkLogs_2.csv](https://github.com/aws-quickstart/quickstart-chainlinklabs-chainlink-node/files/7531500/log-events-viewer-result_ChainlinkLogs_2.csv)
[log-events-viewer-result_ChainlinkLogs_1.csv](https://github.com/aws-quickstart/quickstart-chainlinklabs-chainlink-node/files/7531501/log-events-viewer-result_ChainlinkLogs_1.csv)
[log-events-viewer-result_ChainlinkNodeInitLogGroup_2.csv](https://github.com/aws-quickstart/quickstart-chainlinklabs-chainlink-node/files/7531502/log-events-viewer-result_ChainlinkNodeInitLogGroup_2.csv)

**Comment by dangitsdavid** [comment] 2021-11-15 06:24
The `failed to initialize ORM: initializeORM` which is related to a db issue. In this case, I am seeing `/tmp/.s.PGSQL.5432: connect: no such file or directory)` which I have ran into this error before. 

Based on a stackoverflow, it seems possibly due to misconfiguration of the psql db:
https://stackoverflow.com/questions/42653690/psql-could-not-connect-to-server-no-such-file-or-directory-5432-error/50882756

How was this this psql db configured? Was it done through the QuickStart (i.e., an Aurora cluster)?

**Comment by Malir1988** [comment] 2021-11-15 10:51
I have used the Aurora CLuster provided by the quickstart guide.

See here the Config: (I havent changed anything from the basic configuration except the PW)

![image](https://user-images.githubusercontent.com/71456816/141769067-3e1428ac-8f7b-44d0-98ba-d205051cdecd.png)

**Comment by dangitsdavid** [comment] 2021-11-15 19:21
Did you re-apply the CF template? I have tried to replicate the issue but was not able to run into the issue myself.

Do you have anything important on the Chainlink Nodes currently? If not, can you try to completely tear down and destroy the current stack; then re-deploy it from scratch again?

**Comment by dangitsdavid** [comment] 2021-11-16 17:14
Hey @Malir1988, can you check your db password for PostgreSQL, I dug a little deeper into your logs and found this error message:
`"msg":"invalid database url %spostgresql://postgresadmin:xxxx@xxxx:5432/PostgresDB"`

I've noted some special characters which requires percent encoding in the `postgresql://connection_string`.
https://www.postgresql.org/docs/11/libpq-connect.html#id-1.7.3.8.3.6

> Percent-encoding may be used to include symbols with special meaning in any of the URI parts, e.g., replace = with %3D.

Can you try removing any special characters and try again? I've confirmed the `_` does not require percent encoding so for some security at least have that special character `_` in the db password.

**Comment by Malir1988** [comment] 2021-11-16 20:30
Hello,
I have changed the PW. now everything is working fine.

==> I have also used  _ as the required special character, thanks for your help and effort.

BR Malir

**Closed** 2021-11-16 20:30 UTC

**Comment by Malir1988** [comment] 2021-11-16 20:31
Hello,
I have changed the PW. now everything is working fine.

==> I have also used  _ as the required special character, thanks for your help and effort.

BR Malir
